apiVersion: v1
kind: Service
metadata:
  name: dwarf-app-service
spec:
  selector:
    app: dwarf-app-updated
    ssd: "true"
  ports:
    - protocol: TCP
      port: 8201
      targetPort: 8082
  type: NodePort
